(ns career-ops.daemon.data
  "Content data for the Daemon MCP server tools.
  Each function returns a string that serves as the tool's response content.")

(def about
  (str
   "# Headhunter-Agent\n\n"
   "A **Local-First, Privacy-Preserving Multi-Agent System (MAS)** built for deep candidate profiling, "
   "strategic job evaluation, and interview preparation.\n\n"
   "**Version:** 1.0.0  \n"
   "**Language:** Clojure (JVM + Babashka)  \n"
   "**License:** MIT  \n"
   "**Repository:** https://gitlab.com/nurazhar/headhunter-agent  \n"
   "**Philosophy:** Privacy by design, zero web stack, factual and evidence-based.\n\n"
   "The system runs entirely locally as a native Clojure Desktop GUI using cljfx (JavaFX). "
   "No web browsers, no local web servers, and zero JavaScript.\n\n"
   "### Core Capabilities\n"
   "- **Data Vault** — Deep profiler + STAR story extraction from unstructured data\n"
   "- **Multi-Agent Evaluator** — 3-stage pipeline (Legitimacy → Fit Analysis → Cheat Sheet)\n"
   "- **Interview Prep Center** — STAR story cross-referencing against job descriptions\n"
   "- **ATS-Tailored PDF Generator** — Compile targeted resumes via Typst\n"
   "- **Application Pipeline Tracker** — Markdown-based visual pipeline\n"
   "- **M2M Protocol** — Decentralized, cryptographic job application pipeline"))

(def architecture
  (str
   "# Architecture\n\n"
   "```\n"
   "┌──────────────────────────────────────────────────────────┐\n"
   "│                   HEADHUNTER-AGENT                       │\n"
   "│           Local-First MAS Desktop Console                │\n"
   "├──────────────────────────────────────────────────────────┤\n"
   "│                                                          │\n"
   "│  ┌──────────────┐    ┌──────────────┐   ┌─────────────┐ │\n"
   "│  │  CLI (bb.edn) │    │ GUI (cljfx)  │   │ M2M Protocol│ │\n"
   "│  │  core.clj     │    │  gui.clj     │   │  m2m/*.clj  │ │\n"
   "│  └──────┬───────┘    └──────┬───────┘   └──────┬──────┘ │\n"
   "│         │                   │                    │        │\n"
   "│         └──────────┬────────┘                    │        │\n"
   "│                    │                             │        │\n"
   "│         ┌──────────▼──────────┐                  │        │\n"
   "│         │  Gemini API Gateway  │                  │        │\n"
   "│         │  (evaluator.clj)     │                  │        │\n"
   "│         └──────────┬──────────┘                  │        │\n"
   "│                    │                             │        │\n"
   "│  ┌─────────────────▼─────────────────────────────┘        │\n"
   "│  │  Modules:                                              │\n"
   "│  │  - profiler.clj  (Data Vault Extraction)               │\n"
   "│  │  - evaluator.clj (3-Stage MAS Pipeline)                │\n"
   "│  │  - interview.clj (STAR Story Interview Prep)           │\n"
   "│  │  - pdf.clj       (ATS Tailored PDF Compilation)        │\n"
   "│  │  - tracker.clj   (Application Pipeline Tracker)        │\n"
   "│  └────────────────────────────────────────────────────────┘\n"
   "│                                                          │\n"
   "│  ┌──────────────────────────────────────────────────────┐│\n"
   "│  │  Local Data (User Layer - NEVER auto-updated)        ││\n"
   "│  │  data/master-profile.edn   data/star-stories.edn      ││\n"
   "│  │  data/applications.md      reports/*                  ││\n"
   "│  │  cv.md                     config/profile.yml         ││\n"
   "│  │  output/*                   jds/*                     ││\n"
   "│  └──────────────────────────────────────────────────────┘│\n"
   "└──────────────────────────────────────────────────────────┘\n"
   "```\n\n"
   "### Technology Stack\n"
   "- **Language:** Clojure 1.12 (JVM) / Babashka (native)\n"
   "- **GUI:** cljfx (JavaFX wrapper)\n"
   "- **AI:** Google Gemini API (model-agnostic design)\n"
   "- **PDF:** Typst typesetting system\n"
   "- **JSON:** Cheshire\n"
   "- **HTTP:** babashka http-client\n"
   "- **Crypto:** Ed25519 (Java java.security)\n"
   "- **M2M Protocol:** DNS TXT discovery + JSON-LD + Ed25519 signatures\n\n"
   "### Key Design Decisions\n"
   "1. Privacy-first: All data stays local as .edn / .md files\n"
   "2. No web stack: Native JavaFX desktop GUI, no browsers, no JS\n"
   "3. Babashka compatible: Same source works in JVM Clojure and Babashka\n"
   "4. Gemini-powered AI: All ML through Google Gemini API\n"
   "5. Markdown-based tracker: Simple, human-readable, git-friendly\n"
   "6. Typst for PDF: Modern typesetting replacing LaTeX/HTML-to-PDF\n"
   "7. Ed25519 for M2M: Modern cryptography for decentralized job applications\n"
   "8. Dual interface: Full GUI desktop app + terminal CLI for automation"))

(def modules
  (str
   "# Modules\n\n"
   "## 1. Data Vault (profiler.clj)\n"
   "Single-shot extraction of `master_profile` + `star_stories` from unstructured raw text "
   "(LinkedIn dump, CV text). Uses Gemini with temperature 0.2 for consistency. "
   "Outputs strict JSON saved to `data/master-profile.edn` and `data/star-stories.edn`.\n\n"
   "## 2. Multi-Agent Evaluator (evaluator.clj)\n"
   "3-stage sequential MAS pipeline:\n"
   "- **Agent 1 (Legitimacy):** Parses JD, checks Fair Consideration Framework (FCF) compliance, "
   "identifies red flags. Outputs structured summary block.\n"
   "- **Agent 2 (Fit Analysis):** Brutal comparison of Master Profile vs JD, exact gaps/strengths, "
   "GO/NO-GO recommendation.\n"
   "- **Agent 3 (Cheat Sheet):** Pre-interview cheat sheet: business model, tech stack, "
   "cold outreach strategy with titles + templates.\n\n"
   "## 3. Interview Prep (interview.clj)\n"
   "Cross-references STAR stories library against JD. Predicts 5 most likely interview questions "
   "with STAR mappings, delivery advice, and Reflections column.\n\n"
   "## 4. PDF Resume Generator (pdf.clj)\n"
   "Sends CV + JD to Gemini with ATS-tailoring prompt. Uses structured JSON output (responseMimeType). "
   "Temperature 0.2. Compiles via Typst into a targeted PDF resume.\n\n"
   "## 5. Pipeline Tracker (tracker.clj)\n"
   "Markdown-based application tracker at `data/applications.md`. "
   "Table format with ID, Date, Company, Role, Score, Status, PDF, Report, Notes. "
   "Supports add, list, and mark-PDF-ready operations.\n\n"
   "## 6. M2M Protocol (m2m/*.clj)\n"
   "Decentralized, cryptographic job application pipeline. 7 files:\n"
   "- `core.clj` — CLI entry point and routing\n"
   "- `crypto.clj` — Ed25519 key generation, signing, verification\n"
   "- `schema.clj` — JSON-LD schema validation and generation\n"
   "- `registry.clj` — DNS + directory discovery client\n"
   "- `directory.clj` — Babashka directory server (optional)\n"
   "- `fetch.clj` — JSON-LD job posting HTTP fetcher\n"
   "- `submit.clj` — Signed application package builder\n"
   "- `verify.clj` — Inbound signature verification"))

(def m2m-spec
  (str
   "# M2M Job Application Protocol v1.0.0\n\n"
   "**Machine-to-Machine** job application pipeline. No browsers, no CAPTCHAs, no manual portals.\n\n"
   "### Sub-Protocols\n\n"
   "| Sub-protocol | Description |\n"
   "|---|---|\n"
   "| **Discovery** | Locate employer endpoints via DNS TXT (`_m2m-apply.<domain>`) or directory |\n"
   "| **Fetch** | Retrieve machine-readable job postings (JSON-LD extending schema.org) |\n"
   "| **Verify** | Ed25519 mutual identity verification |\n"
   "| **Submit** | Signed application package delivery + signed acknowledgment |\n\n"
   "### Data Flow\n"
   "1. DNS TXT lookup on `_m2m-apply.employer.example`\n"
   "2. Receive endpoint URL + public key\n"
   "3. GET job posting as JSON-LD from employer\n"
   "4. Run MAS evaluation pipeline\n"
   "5. Tailor resume via Gemini + compile PDF via Typst\n"
   "6. Build signed ApplicationPackage (Ed25519)\n"
   "7. POST multipart form with JSON-LD payload + PDF attachment\n"
   "8. Receive signed acknowledgment with application ID\n\n"
   "### Cryptography\n"
   "- Ed25519 keypairs (Java `java.security`)\n"
   "- Every application is signed; every attachment has its own digest + signature\n"
   "- DNSSEC-ready, DID-compatible (`did:key:`)\n"
   "- Future-proofed for encrypted submissions\n\n"
   "### Threat Model\n"
   "| Threat | Mitigation |\n"
   "|---|---|\n"
   "| Impersonation | DNS-based key binding + TLS |\n"
   "| Replay attack | Timestamp + nonce in package |\n"
   "| Tampered resume | Attachment digest + separate signature |\n"
   "| Man-in-the-middle | TLS + signed payloads for end-to-end integrity |\n\n"
   "### No-CAPTCHA Guarantee\n"
   "- Endpoints opt-in by publishing `m2m:acceptsSignedApplications: true`\n"
   "- Signed identity replaces cookie/session/auth-wall\n"
   "- Rate limiting by public key fingerprint, not IP"))

(def config-ref
  (str
   "# Configuration Reference\n\n"
   "## Environment (.env)\n"
   "```\n"
   "GEMINI_API_KEY=your_key_here\n"
   "```\n\n"
   "## Profile (config/profile.yml)\n"
   "- Candidate identity (name, email, phone, location, NS status)\n"
   "- Target roles (primary, secondary, adjacent archetypes)\n"
   "- Narrative (headline, exit story, superpowers, proof points)\n"
   "- Compensation targets (monthly base, AWS, bonus, currency SGD)\n"
   "- Location preferences (Hybrid, Singapore Citizen)\n"
   "- CV output format\n\n"
   "## Archetypes\n"
   "- AI Platform / LLMOps\n"
   "- Agentic / Automation\n"
   "- Technical AI PM\n"
   "- AI Solutions Architect\n"
   "- AI Forward Deployed\n"
   "- AI Transformation\n\n"
   "## Scoring System\n"
   "- 6 evaluation blocks (A-F)\n"
   "- Global score 1-5\n"
   "- Legitimacy Block G: signals table with reliability ratings\n\n"
   "## Data Contract\n"
   "Two-layer file ownership model:\n"
   "- **User Layer** (NEVER auto-updated): `cv.md`, `config/profile.yml`, `modes/_profile.md`, "
   "`data/applications.md`, `reports/*`, `output/*`, `jds/*`, `.env`, `resume_data.json`\n"
   "- **System Layer** (safe to replace): `src/*`, `bb.edn`, `modes/_shared.md`, "
   "`resume.typ`, `setup.sh`, `setup.bat`, `README.md`, `LICENSE`, `DATA_CONTRACT.md`"))

(def usage
  (str
   "# Usage Guide\n\n"
   "## Desktop GUI\n"
   "```bash\n"
   "clj -M:run\n"
   "```\n"
   "Opens a native JavaFX window with 4 tabs:\n"
   "1. **Data Vault** — Extract master profile + STAR stories\n"
   "2. **JD Evaluator** — 3-stage MAS pipeline with score visualization\n"
   "3. **Interview Prep** — Generate STAR-mapped prep sheets\n"
   "4. **Pipeline Tracker** — Visual application pipeline cards\n\n"
   "## CLI (Babashka)\n"
   "```bash\n"
   "bb profile --extract /path/to/linkedin-dump.txt\n"
   "bb evaluate --file ./jds/defence-collective.txt\n"
   "bb interview --file ./jds/defence-collective.txt\n"
   "bb pdf --file ./jds/defence-collective.txt\n"
   "bb tracker list\n"
   "bb tracker mark 3 --pdf ./output/cv-company-2026-06-24.pdf\n"
   "```\n\n"
   "## M2M Protocol\n"
   "```bash\n"
   "bb bb-m2m keygen                              # Generate Ed25519 identity\n"
   "bb bb-m2m discover employer.example            # DNS discovery\n"
   "bb bb-m2m fetch https://employer.example/jobs/42  # Fetch job posting\n"
   "bb bb-m2m apply https://employer.example/jobs/42  # Full pipeline\n"
   "bb bb-m2m verify ./package.json                 # Verify signed package\n"
   "bb bb-m2m serve --port 8080                     # Start directory server\n"
   "```\n\n"
   "## Installation\n"
   "1. JDK 11+, Clojure CLI, Babashka (optional)\n"
   "2. Clone: `git clone https://gitlab.com/nurazhar/headhunter-agent.git`\n"
   "3. Create `.env` with `GEMINI_API_KEY`\n"
   "4. Run setup: `bash setup.sh` (creates config files from examples)"))

(def data-contract
  (str
   "# Data Contract\n\n"
   "Defines which files belong to the **system** (auto-updatable) and which belong to the "
   "**user** (never touched by updates).\n\n"
   "## User Layer (NEVER auto-updated)\n\n"
   "| File / Folder | Purpose |\n"
   "|---|---|\n"
   "| `cv.md` | Your CV in Markdown |\n"
   "| `config/profile.yml` | Your identity, targets, comp range |\n"
   "| `modes/_profile.md` | Your archetypes, narrative, negotiation scripts |\n"
   "| `data/applications.md` | Your application tracker database |\n"
   "| `reports/*` | Your generated evaluation reports |\n"
   "| `output/*` | Your compiled tailored PDF resumes |\n"
   "| `jds/*` | Your saved job descriptions |\n"
   "| `.env` | Your local API keys and secrets |\n"
   "| `resume_data.json` | Temporary resume JSON file generated by Gemini |\n\n"
   "## System Layer (safe to auto-update)\n\n"
   "| File / Folder | Purpose |\n"
   "|---|---|\n"
   "| `modes/_shared.md` | Scoring system, global rules, tools |\n"
   "| `modes/oferta.md` | Evaluation mode instructions |\n"
   "| `src/*` | Clojure source files |\n"
   "| `bb.edn` | Babashka task configuration |\n"
   "| `resume.typ` | Base Typst file for compiling PDFs |\n"
   "| `resume_template.typ` | Layout and styles template |\n"
   "| `setup.sh` / `setup.bat` | Platform setup scripts |\n"
   "| `README.md` | System-owned documentation |\n"
   "| `LICENSE` | MIT License |\n"
   "| `DATA_CONTRACT.md` | This file |\n\n"
   "## The Rule\n"
   "**If a file is in the User Layer, no update process may read, modify, or delete it.**\n"
   "**If a file is in the System Layer, it can be safely replaced with the latest version.**"))

(def projects
  (str
   "# Projects\n\n"
   "### Current: headhunter-agent v1.0.0\n"
   "Local-first, privacy-preserving MAS desktop console for job hunting.\n"
   "- Completing the M2M protocol (P4-P5)\n"
   "- Adding employer-side verification library\n"
   "- Test suite and CI integration\n\n"
   "### Related Ecosystem\n"
   "- **butler** — Personal AI butler in Clojure/Babashka\n"
   "- **bunker** — Identity governance and access management\n"
   "- **bsv-clj** — Bitcoin SV Clojure toolkit\n"
   "- **pdpa-sg-clj** — PDPA compliance scanner for Singapore\n"
   "- **paperclip-clj** — Deterministic business engine"))

(def all-data
  (str
   "# Headhunter-Agent — Complete Reference\n\n"
   "## About\n" about "\n\n"
   "## Architecture\n" architecture "\n\n"
   "## Modules\n" modules "\n\n"
   "## M2M Protocol\n" m2m-spec "\n\n"
   "## Configuration\n" config-ref "\n\n"
   "## Usage\n" usage "\n\n"
   "## Data Contract\n" data-contract "\n\n"
   "## Projects\n" projects))
